version: "3.9"

services:

  postgresDB:
    image: postgres:14.4
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "DemorDB"

  demor-backend:
    build: ./
    depends_on:
      - postgresDB
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=production"
