CREATE TABLE IF NOT EXISTS USERS(
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    USER_ROLE VARCHAR(255) NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    ENABLED BOOLEAN NOT NULL
);